//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SenhaixFreqWriter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_zh_hans {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_zh_hans() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SenhaixFreqWriter.Properties.Resources.zh-hans", typeof(Resources_zh_hans).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string abort {
            get {
                return ResourceManager.GetString("abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于.
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 森海克斯通用写频软件.
        /// </summary>
        public static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动备份：.
        /// </summary>
        public static string auto_backup {
            get {
                return ResourceManager.GetString("auto_backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用端口自动选择.
        /// </summary>
        public static string auto_port_sel {
            get {
                return ResourceManager.GetString("auto_port_sel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - 备份周期（s）:.
        /// </summary>
        public static string backup_period {
            get {
                return ResourceManager.GetString("backup_period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 连接蓝牙.
        /// </summary>
        public static string bt_connection {
            get {
                return ResourceManager.GetString("bt_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 插件参数：.
        /// </summary>
        public static string bt_plugin_args {
            get {
                return ResourceManager.GetString("bt_plugin_args", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 蓝牙插件名称:.
        /// </summary>
        public static string bt_plugin_name {
            get {
                return ResourceManager.GetString("bt_plugin_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 简体中文.
        /// </summary>
        public static string chinese {
            get {
                return ResourceManager.GetString("chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择.
        /// </summary>
        public static string choose {
            get {
                return ResourceManager.GetString("choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择设备.
        /// </summary>
        public static string choose_device {
            get {
                return ResourceManager.GetString("choose_device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 如果您在开启软件前已接入写频线，同时没有其他的USB串口设备，那么此时软件应该已帮您自动选择好端口了。
        ///如果软件未帮您选择好端口，请您按照以下步骤选择串口：
        ///Windows系统:
        ///    1、确认好您已安装对应写频线的驱动；
        ///    2、打开设备管理器，在“端口”一栏中查找您的写频线，名称应类似于“USB-SERIAL CH340 (COM12)”
        ///    3、回到软件中，点击下拉框选择对应的端口即可。
        ///macOS:
        ///    1、确认您已安装好写频线的驱动（ch340可不用安装）；
        ///    2、移除其他使用串口的设备；
        ///    3、点击下拉框，选择带“cu”的选项，例如：/dev/cu.usbserial-210即可；.
        /// </summary>
        public static string choose_help {
            get {
                return ResourceManager.GetString("choose_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择端口(点击下拉选择):.
        /// </summary>
        public static string choose_port {
            get {
                return ResourceManager.GetString("choose_port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提交：.
        /// </summary>
        public static string commit {
            get {
                return ResourceManager.GetString("commit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编译时间：.
        /// </summary>
        public static string compile_time {
            get {
                return ResourceManager.GetString("compile_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定.
        /// </summary>
        public static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 连接设备.
        /// </summary>
        public static string conn_bt {
            get {
                return ResourceManager.GetString("conn_bt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用详细调试输出.
        /// </summary>
        public static string detailed_log {
            get {
                return ResourceManager.GetString("detailed_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 禁用ssid过滤.
        /// </summary>
        public static string disable_ssid_filter {
            get {
                return ResourceManager.GetString("disable_ssid_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 禁用弱信号限制(win).
        /// </summary>
        public static string disable_weak_signal {
            get {
                return ResourceManager.GetString("disable_weak_signal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 英语.
        /// </summary>
        public static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 失败！.
        /// </summary>
        public static string failed {
            get {
                return ResourceManager.GetString("failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hint：如果在windows下始终找不到目标设备，不妨试着点我重启一下蓝牙~.
        /// </summary>
        public static string hint_bt {
            get {
                return ResourceManager.GetString("hint_bt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 如何选择？.
        /// </summary>
        public static string how2choose {
            get {
                return ResourceManager.GetString("how2choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to （内部版本）.
        /// </summary>
        public static string internal_version {
            get {
                return ResourceManager.GetString("internal_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - 手动控制蓝牙插件（高级）.
        /// </summary>
        public static string manual_call {
            get {
                return ResourceManager.GetString("manual_call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , 最大数量:.
        /// </summary>
        public static string max_backups {
            get {
                return ResourceManager.GetString("max_backups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开备份目录.
        /// </summary>
        public static string open_backup_dir {
            get {
                return ResourceManager.GetString("open_backup_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 端口.
        /// </summary>
        public static string port {
            get {
                return ResourceManager.GetString("port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仓库.
        /// </summary>
        public static string repo {
            get {
                return ResourceManager.GetString("repo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPC调用.
        /// </summary>
        public static string rpc_call {
            get {
                return ResourceManager.GetString("rpc_call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 扫描设备.
        /// </summary>
        public static string scan_bt {
            get {
                return ResourceManager.GetString("scan_bt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设备名.
        /// </summary>
        public static string ssid {
            get {
                return ResourceManager.GetString("ssid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据存储目录.
        /// </summary>
        public static string storage_dir {
            get {
                return ResourceManager.GetString("storage_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请以sudo权限打开软件!.
        /// </summary>
        public static string sudo {
            get {
                return ResourceManager.GetString("sudo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 语言：.
        /// </summary>
        public static string switch_language {
            get {
                return ResourceManager.GetString("switch_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 致谢.
        /// </summary>
        public static string thanksto {
            get {
                return ResourceManager.GetString("thanksto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 版本号：.
        /// </summary>
        public static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注意.
        /// </summary>
        public static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
    }
}
