//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SenhaixFreqWriter.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_zh {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_zh() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SenhaixFreqWriter.Properties.Resources_zh", typeof(Resources_zh).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        public static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
        
        public static string commit {
            get {
                return ResourceManager.GetString("commit", resourceCulture);
            }
        }
        
        public static string compile_time {
            get {
                return ResourceManager.GetString("compile_time", resourceCulture);
            }
        }
        
        public static string internal_version {
            get {
                return ResourceManager.GetString("internal_version", resourceCulture);
            }
        }
        
        public static string thanksto {
            get {
                return ResourceManager.GetString("thanksto", resourceCulture);
            }
        }
        
        public static string repo {
            get {
                return ResourceManager.GetString("repo", resourceCulture);
            }
        }
        
        public static string hint_bt {
            get {
                return ResourceManager.GetString("hint_bt", resourceCulture);
            }
        }
        
        public static string ssid {
            get {
                return ResourceManager.GetString("ssid", resourceCulture);
            }
        }
        
        public static string disable_weak_signal {
            get {
                return ResourceManager.GetString("disable_weak_signal", resourceCulture);
            }
        }
        
        public static string disable_ssid_filter {
            get {
                return ResourceManager.GetString("disable_ssid_filter", resourceCulture);
            }
        }
        
        public static string rpc_call {
            get {
                return ResourceManager.GetString("rpc_call", resourceCulture);
            }
        }
        
        public static string manual_call {
            get {
                return ResourceManager.GetString("manual_call", resourceCulture);
            }
        }
        
        public static string conn_bt {
            get {
                return ResourceManager.GetString("conn_bt", resourceCulture);
            }
        }
        
        public static string scan_bt {
            get {
                return ResourceManager.GetString("scan_bt", resourceCulture);
            }
        }
        
        public static string bt_connection {
            get {
                return ResourceManager.GetString("bt_connection", resourceCulture);
            }
        }
        
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        public static string choose_device {
            get {
                return ResourceManager.GetString("choose_device", resourceCulture);
            }
        }
        
        public static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        public static string sudo {
            get {
                return ResourceManager.GetString("sudo", resourceCulture);
            }
        }
        
        public static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        public static string choose_port {
            get {
                return ResourceManager.GetString("choose_port", resourceCulture);
            }
        }
        
        public static string port {
            get {
                return ResourceManager.GetString("port", resourceCulture);
            }
        }
        
        public static string choose_help {
            get {
                return ResourceManager.GetString("choose_help", resourceCulture);
            }
        }
        
        public static string how2choose {
            get {
                return ResourceManager.GetString("how2choose", resourceCulture);
            }
        }
        
        public static string abort {
            get {
                return ResourceManager.GetString("abort", resourceCulture);
            }
        }
        
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        public static string auto_backup {
            get {
                return ResourceManager.GetString("auto_backup", resourceCulture);
            }
        }
        
        public static string backup_period {
            get {
                return ResourceManager.GetString("backup_period", resourceCulture);
            }
        }
        
        public static string max_backups {
            get {
                return ResourceManager.GetString("max_backups", resourceCulture);
            }
        }
        
        public static string open_backup_dir {
            get {
                return ResourceManager.GetString("open_backup_dir", resourceCulture);
            }
        }
        
        public static string failed {
            get {
                return ResourceManager.GetString("failed", resourceCulture);
            }
        }
        
        public static string auto_port_sel {
            get {
                return ResourceManager.GetString("auto_port_sel", resourceCulture);
            }
        }
        
        public static string detailed_log {
            get {
                return ResourceManager.GetString("detailed_log", resourceCulture);
            }
        }
        
        public static string storage_dir {
            get {
                return ResourceManager.GetString("storage_dir", resourceCulture);
            }
        }
        
        public static string choose {
            get {
                return ResourceManager.GetString("choose", resourceCulture);
            }
        }
        
        public static string bt_plugin_name {
            get {
                return ResourceManager.GetString("bt_plugin_name", resourceCulture);
            }
        }
        
        public static string bt_plugin_args {
            get {
                return ResourceManager.GetString("bt_plugin_args", resourceCulture);
            }
        }
        
        public static string chinese {
            get {
                return ResourceManager.GetString("chinese", resourceCulture);
            }
        }
        
        public static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        public static string switch_language {
            get {
                return ResourceManager.GetString("switch_language", resourceCulture);
            }
        }
        
        public static string pwr_high {
            get {
                return ResourceManager.GetString("pwr_high", resourceCulture);
            }
        }
        
        public static string pwr_mid {
            get {
                return ResourceManager.GetString("pwr_mid", resourceCulture);
            }
        }
        
        public static string pwr_low {
            get {
                return ResourceManager.GetString("pwr_low", resourceCulture);
            }
        }
        
        public static string wide {
            get {
                return ResourceManager.GetString("wide", resourceCulture);
            }
        }
        
        public static string narrow {
            get {
                return ResourceManager.GetString("narrow", resourceCulture);
            }
        }
        
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        public static string press_ptt {
            get {
                return ResourceManager.GetString("press_ptt", resourceCulture);
            }
        }
        
        public static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }
        
        public static string release_ptt {
            get {
                return ResourceManager.GetString("release_ptt", resourceCulture);
            }
        }
        
        public static string on {
            get {
                return ResourceManager.GetString("on", resourceCulture);
            }
        }
        
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        public static string press_and_release_ptt {
            get {
                return ResourceManager.GetString("press_and_release_ptt", resourceCulture);
            }
        }
        
        public static string high_sensitivity {
            get {
                return ResourceManager.GetString("high_sensitivity", resourceCulture);
            }
        }
        
        public static string off {
            get {
                return ResourceManager.GetString("off", resourceCulture);
            }
        }
        
        public static string mid_sensitivity {
            get {
                return ResourceManager.GetString("mid_sensitivity", resourceCulture);
            }
        }
        
        public static string low_sensitivity {
            get {
                return ResourceManager.GetString("low_sensitivity", resourceCulture);
            }
        }
        
        public static string default_msg {
            get {
                return ResourceManager.GetString("default_msg", resourceCulture);
            }
        }
        
        public static string bat_volt {
            get {
                return ResourceManager.GetString("bat_volt", resourceCulture);
            }
        }
        
        public static string beep {
            get {
                return ResourceManager.GetString("beep", resourceCulture);
            }
        }
        
        public static string voice {
            get {
                return ResourceManager.GetString("voice", resourceCulture);
            }
        }
        
        public static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        public static string low_gain {
            get {
                return ResourceManager.GetString("low_gain", resourceCulture);
            }
        }
        
        public static string mid_gain {
            get {
                return ResourceManager.GetString("mid_gain", resourceCulture);
            }
        }
        
        public static string high_gain {
            get {
                return ResourceManager.GetString("high_gain", resourceCulture);
            }
        }
        
        public static string time_scan {
            get {
                return ResourceManager.GetString("time_scan", resourceCulture);
            }
        }
        
        public static string carrier_scan {
            get {
                return ResourceManager.GetString("carrier_scan", resourceCulture);
            }
        }
        
        public static string search_scan {
            get {
                return ResourceManager.GetString("search_scan", resourceCulture);
            }
        }
        
        public static string send_sos_code {
            get {
                return ResourceManager.GetString("send_sos_code", resourceCulture);
            }
        }
        
        public static string send_sos_voice {
            get {
                return ResourceManager.GetString("send_sos_voice", resourceCulture);
            }
        }
        
        public static string live_sos {
            get {
                return ResourceManager.GetString("live_sos", resourceCulture);
            }
        }
        
        public static string allow {
            get {
                return ResourceManager.GetString("allow", resourceCulture);
            }
        }
        
        public static string forbid {
            get {
                return ResourceManager.GetString("forbid", resourceCulture);
            }
        }
        
        public static string normal_open {
            get {
                return ResourceManager.GetString("normal_open", resourceCulture);
            }
        }
        
        public static string chan_name {
            get {
                return ResourceManager.GetString("chan_name", resourceCulture);
            }
        }
        
        public static string chan_num {
            get {
                return ResourceManager.GetString("chan_num", resourceCulture);
            }
        }
        
        public static string freq {
            get {
                return ResourceManager.GetString("freq", resourceCulture);
            }
        }
        
        public static string chan_mode {
            get {
                return ResourceManager.GetString("chan_mode", resourceCulture);
            }
        }
        
        public static string freq_mode {
            get {
                return ResourceManager.GetString("freq_mode", resourceCulture);
            }
        }
        
        public static string switch_pwr {
            get {
                return ResourceManager.GetString("switch_pwr", resourceCulture);
            }
        }
        
        public static string fm {
            get {
                return ResourceManager.GetString("fm", resourceCulture);
            }
        }
        
        public static string listen {
            get {
                return ResourceManager.GetString("listen", resourceCulture);
            }
        }
        
        public static string scan_freq {
            get {
                return ResourceManager.GetString("scan_freq", resourceCulture);
            }
        }
        
        public static string sos {
            get {
                return ResourceManager.GetString("sos", resourceCulture);
            }
        }
        
        public static string weather {
            get {
                return ResourceManager.GetString("weather", resourceCulture);
            }
        }
        
        public static string scan {
            get {
                return ResourceManager.GetString("scan", resourceCulture);
            }
        }
        
        public static string remote_tone_scan {
            get {
                return ResourceManager.GetString("remote_tone_scan", resourceCulture);
            }
        }
        
        public static string tx_start {
            get {
                return ResourceManager.GetString("tx_start", resourceCulture);
            }
        }
        
        public static string tx_end {
            get {
                return ResourceManager.GetString("tx_end", resourceCulture);
            }
        }
        
        public static string both {
            get {
                return ResourceManager.GetString("both", resourceCulture);
            }
        }
        
        public static string chan_num_and_chan_name {
            get {
                return ResourceManager.GetString("chan_num_and_chan_name", resourceCulture);
            }
        }
        
        public static string chan_num_and_freq {
            get {
                return ResourceManager.GetString("chan_num_and_freq", resourceCulture);
            }
        }
        
        public static string key_sidetone {
            get {
                return ResourceManager.GetString("key_sidetone", resourceCulture);
            }
        }
        
        public static string idcode_sidetone {
            get {
                return ResourceManager.GetString("idcode_sidetone", resourceCulture);
            }
        }
        
        public static string key_and_idcode_sidetone {
            get {
                return ResourceManager.GetString("key_and_idcode_sidetone", resourceCulture);
            }
        }
        
        public static string tx_on_release {
            get {
                return ResourceManager.GetString("tx_on_release", resourceCulture);
            }
        }
        
        public static string tx_on_press {
            get {
                return ResourceManager.GetString("tx_on_press", resourceCulture);
            }
        }
        
        public static string tx_on_both {
            get {
                return ResourceManager.GetString("tx_on_both", resourceCulture);
            }
        }
        
        public static string default_img1 {
            get {
                return ResourceManager.GetString("default_img1", resourceCulture);
            }
        }
        
        public static string default_img2 {
            get {
                return ResourceManager.GetString("default_img2", resourceCulture);
            }
        }
        
        public static string default_word {
            get {
                return ResourceManager.GetString("default_word", resourceCulture);
            }
        }
        
        public static string normal_pwr_save {
            get {
                return ResourceManager.GetString("normal_pwr_save", resourceCulture);
            }
        }
        
        public static string super_pwr_save {
            get {
                return ResourceManager.GetString("super_pwr_save", resourceCulture);
            }
        }
        
        public static string deep_pwr_save {
            get {
                return ResourceManager.GetString("deep_pwr_save", resourceCulture);
            }
        }
        
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        public static string serial_no {
            get {
                return ResourceManager.GetString("serial_no", resourceCulture);
            }
        }
        
        public static string code {
            get {
                return ResourceManager.GetString("code", resourceCulture);
            }
        }
        
        public static string my_id {
            get {
                return ResourceManager.GetString("my_id", resourceCulture);
            }
        }
        
        public static string dtmf_last_time {
            get {
                return ResourceManager.GetString("dtmf_last_time", resourceCulture);
            }
        }
        
        public static string dtmf_break_time {
            get {
                return ResourceManager.GetString("dtmf_break_time", resourceCulture);
            }
        }
        
        public static string current_freq {
            get {
                return ResourceManager.GetString("current_freq", resourceCulture);
            }
        }
        
        public static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        public static string new_cfg {
            get {
                return ResourceManager.GetString("new_cfg", resourceCulture);
            }
        }
        
        public static string open {
            get {
                return ResourceManager.GetString("open", resourceCulture);
            }
        }
        
        public static string saveas {
            get {
                return ResourceManager.GetString("saveas", resourceCulture);
            }
        }
        
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        public static string window {
            get {
                return ResourceManager.GetString("window", resourceCulture);
            }
        }
        
        public static string optional_function {
            get {
                return ResourceManager.GetString("optional_function", resourceCulture);
            }
        }
        
        public static string dtmf {
            get {
                return ResourceManager.GetString("dtmf", resourceCulture);
            }
        }
        
        public static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        public static string write_chan {
            get {
                return ResourceManager.GetString("write_chan", resourceCulture);
            }
        }
        
        public static string read_chan {
            get {
                return ResourceManager.GetString("read_chan", resourceCulture);
            }
        }
        
        public static string rw_freq {
            get {
                return ResourceManager.GetString("rw_freq", resourceCulture);
            }
        }
        
        public static string modify_boot_img {
            get {
                return ResourceManager.GetString("modify_boot_img", resourceCulture);
            }
        }
        
        public static string sat_helper {
            get {
                return ResourceManager.GetString("sat_helper", resourceCulture);
            }
        }
        
        public static string others {
            get {
                return ResourceManager.GetString("others", resourceCulture);
            }
        }
        
        public static string theme_color {
            get {
                return ResourceManager.GetString("theme_color", resourceCulture);
            }
        }
        
        public static string tools {
            get {
                return ResourceManager.GetString("tools", resourceCulture);
            }
        }
        
        public static string switch_device {
            get {
                return ResourceManager.GetString("switch_device", resourceCulture);
            }
        }
        
        public static string debug_function {
            get {
                return ResourceManager.GetString("debug_function", resourceCulture);
            }
        }
        
        public static string open_debug_window {
            get {
                return ResourceManager.GetString("open_debug_window", resourceCulture);
            }
        }
        
        public static string fetch_hid {
            get {
                return ResourceManager.GetString("fetch_hid", resourceCulture);
            }
        }
        
        public static string read_freq {
            get {
                return ResourceManager.GetString("read_freq", resourceCulture);
            }
        }
        
        public static string write_freq {
            get {
                return ResourceManager.GetString("write_freq", resourceCulture);
            }
        }
        
        public static string no_connected_status {
            get {
                return ResourceManager.GetString("no_connected_status", resourceCulture);
            }
        }
        
        public static string prev_area {
            get {
                return ResourceManager.GetString("prev_area", resourceCulture);
            }
        }
        
        public static string next_area {
            get {
                return ResourceManager.GetString("next_area", resourceCulture);
            }
        }
        
        public static string skip {
            get {
                return ResourceManager.GetString("skip", resourceCulture);
            }
        }
        
        public static string cut {
            get {
                return ResourceManager.GetString("cut", resourceCulture);
            }
        }
        
        public static string copy {
            get {
                return ResourceManager.GetString("copy", resourceCulture);
            }
        }
        
        public static string paste {
            get {
                return ResourceManager.GetString("paste", resourceCulture);
            }
        }
        
        public static string clear_sel_chan {
            get {
                return ResourceManager.GetString("clear_sel_chan", resourceCulture);
            }
        }
        
        public static string del_chan {
            get {
                return ResourceManager.GetString("del_chan", resourceCulture);
            }
        }
        
        public static string ins_chan {
            get {
                return ResourceManager.GetString("ins_chan", resourceCulture);
            }
        }
        
        public static string combine_chan {
            get {
                return ResourceManager.GetString("combine_chan", resourceCulture);
            }
        }
        
        public static string chan {
            get {
                return ResourceManager.GetString("chan", resourceCulture);
            }
        }
        
        public static string rx_freq {
            get {
                return ResourceManager.GetString("rx_freq", resourceCulture);
            }
        }
        
        public static string tone_dec {
            get {
                return ResourceManager.GetString("tone_dec", resourceCulture);
            }
        }
        
        public static string skip_to_area {
            get {
                return ResourceManager.GetString("skip_to_area", resourceCulture);
            }
        }
        
        public static string tx_freq {
            get {
                return ResourceManager.GetString("tx_freq", resourceCulture);
            }
        }
        
        public static string tone_enc {
            get {
                return ResourceManager.GetString("tone_enc", resourceCulture);
            }
        }
        
        public static string bandwidth {
            get {
                return ResourceManager.GetString("bandwidth", resourceCulture);
            }
        }
        
        public static string power {
            get {
                return ResourceManager.GetString("power", resourceCulture);
            }
        }
        
        public static string area_name {
            get {
                return ResourceManager.GetString("area_name", resourceCulture);
            }
        }
        
        public static string scan_add {
            get {
                return ResourceManager.GetString("scan_add", resourceCulture);
            }
        }
        
        public static string signalling {
            get {
                return ResourceManager.GetString("signalling", resourceCulture);
            }
        }
        
        public static string mute_mode {
            get {
                return ResourceManager.GetString("mute_mode", resourceCulture);
            }
        }
        
        public static string signalling_code {
            get {
                return ResourceManager.GetString("signalling_code", resourceCulture);
            }
        }
        
        public static string sql_level {
            get {
                return ResourceManager.GetString("sql_level", resourceCulture);
            }
        }
        
        public static string tx_timeout {
            get {
                return ResourceManager.GetString("tx_timeout", resourceCulture);
            }
        }
        
        public static string pwr_save_mode {
            get {
                return ResourceManager.GetString("pwr_save_mode", resourceCulture);
            }
        }
        
        public static string vox_switch {
            get {
                return ResourceManager.GetString("vox_switch", resourceCulture);
            }
        }
        
        public static string vox_level {
            get {
                return ResourceManager.GetString("vox_level", resourceCulture);
            }
        }
        
        public static string vox_delay {
            get {
                return ResourceManager.GetString("vox_delay", resourceCulture);
            }
        }
        
        public static string dual_listen {
            get {
                return ResourceManager.GetString("dual_listen", resourceCulture);
            }
        }
        
        public static string rev_rpt_freq {
            get {
                return ResourceManager.GetString("rev_rpt_freq", resourceCulture);
            }
        }
        
        public static string tone_switch {
            get {
                return ResourceManager.GetString("tone_switch", resourceCulture);
            }
        }
        
        public static string tail_clear {
            get {
                return ResourceManager.GetString("tail_clear", resourceCulture);
            }
        }
        
        public static string boot_disp {
            get {
                return ResourceManager.GetString("boot_disp", resourceCulture);
            }
        }
        
        public static string remind_voice {
            get {
                return ResourceManager.GetString("remind_voice", resourceCulture);
            }
        }
        
        public static string scan_mode {
            get {
                return ResourceManager.GetString("scan_mode", resourceCulture);
            }
        }
        
        public static string sos_mode {
            get {
                return ResourceManager.GetString("sos_mode", resourceCulture);
            }
        }
        
        public static string keyboard_lock {
            get {
                return ResourceManager.GetString("keyboard_lock", resourceCulture);
            }
        }
        
        public static string mic_gain {
            get {
                return ResourceManager.GetString("mic_gain", resourceCulture);
            }
        }
        
        public static string current_area {
            get {
                return ResourceManager.GetString("current_area", resourceCulture);
            }
        }
        
        public static string keyboard_lock_time {
            get {
                return ResourceManager.GetString("keyboard_lock_time", resourceCulture);
            }
        }
        
        public static string menu_exit_time {
            get {
                return ResourceManager.GetString("menu_exit_time", resourceCulture);
            }
        }
        
        public static string bglight_time {
            get {
                return ResourceManager.GetString("bglight_time", resourceCulture);
            }
        }
        
        public static string bglight_level {
            get {
                return ResourceManager.GetString("bglight_level", resourceCulture);
            }
        }
        
        public static string tx_code_delay {
            get {
                return ResourceManager.GetString("tx_code_delay", resourceCulture);
            }
        }
        
        public static string tx_end_sound {
            get {
                return ResourceManager.GetString("tx_end_sound", resourceCulture);
            }
        }
        
        public static string a_band_disp_mode {
            get {
                return ResourceManager.GetString("a_band_disp_mode", resourceCulture);
            }
        }
        
        public static string a_band_work_mode {
            get {
                return ResourceManager.GetString("a_band_work_mode", resourceCulture);
            }
        }
        
        public static string b_band_disp_mode {
            get {
                return ResourceManager.GetString("b_band_disp_mode", resourceCulture);
            }
        }
        
        public static string b_band_work_mode {
            get {
                return ResourceManager.GetString("b_band_work_mode", resourceCulture);
            }
        }
        
        public static string key_1_short_press {
            get {
                return ResourceManager.GetString("key_1_short_press", resourceCulture);
            }
        }
        
        public static string key_1_long_press {
            get {
                return ResourceManager.GetString("key_1_long_press", resourceCulture);
            }
        }
        
        public static string key_2_short_press {
            get {
                return ResourceManager.GetString("key_2_short_press", resourceCulture);
            }
        }
        
        public static string key_2_long_press {
            get {
                return ResourceManager.GetString("key_2_long_press", resourceCulture);
            }
        }
        
        public static string pass_rpt_tail_clear {
            get {
                return ResourceManager.GetString("pass_rpt_tail_clear", resourceCulture);
            }
        }
        
        public static string pass_rpt_tail_detect {
            get {
                return ResourceManager.GetString("pass_rpt_tail_detect", resourceCulture);
            }
        }
        
        public static string boot_img_disp_time {
            get {
                return ResourceManager.GetString("boot_img_disp_time", resourceCulture);
            }
        }
        
        public static string bt_voice_gain {
            get {
                return ResourceManager.GetString("bt_voice_gain", resourceCulture);
            }
        }
        
        public static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        public static string callsign {
            get {
                return ResourceManager.GetString("callsign", resourceCulture);
            }
        }
        
        public static string wait_order {
            get {
                return ResourceManager.GetString("wait_order", resourceCulture);
            }
        }
        
        public static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        public static string rx_tone {
            get {
                return ResourceManager.GetString("rx_tone", resourceCulture);
            }
        }
        
        public static string tx_tone {
            get {
                return ResourceManager.GetString("tx_tone", resourceCulture);
            }
        }
        
        public static string sig_system {
            get {
                return ResourceManager.GetString("sig_system", resourceCulture);
            }
        }
        
        public static string step {
            get {
                return ResourceManager.GetString("step", resourceCulture);
            }
        }
        
        public static string busy_lock {
            get {
                return ResourceManager.GetString("busy_lock", resourceCulture);
            }
        }
        
        public static string sig_encode {
            get {
                return ResourceManager.GetString("sig_encode", resourceCulture);
            }
        }
        
        public static string freq_offset_dir {
            get {
                return ResourceManager.GetString("freq_offset_dir", resourceCulture);
            }
        }
        
        public static string freq_offset {
            get {
                return ResourceManager.GetString("freq_offset", resourceCulture);
            }
        }
        
        public static string create_bootimg {
            get {
                return ResourceManager.GetString("create_bootimg", resourceCulture);
            }
        }
        
        public static string img_bgcolor {
            get {
                return ResourceManager.GetString("img_bgcolor", resourceCulture);
            }
        }
        
        public static string input_info {
            get {
                return ResourceManager.GetString("input_info", resourceCulture);
            }
        }
        
        public static string font_color {
            get {
                return ResourceManager.GetString("font_color", resourceCulture);
            }
        }
        
        public static string font {
            get {
                return ResourceManager.GetString("font", resourceCulture);
            }
        }
        
        public static string style {
            get {
                return ResourceManager.GetString("style", resourceCulture);
            }
        }
        
        public static string font_size {
            get {
                return ResourceManager.GetString("font_size", resourceCulture);
            }
        }
        
        public static string x_pos {
            get {
                return ResourceManager.GetString("x_pos", resourceCulture);
            }
        }
        
        public static string y_pos {
            get {
                return ResourceManager.GetString("y_pos", resourceCulture);
            }
        }
        
        public static string center {
            get {
                return ResourceManager.GetString("center", resourceCulture);
            }
        }
        
        public static string add_text {
            get {
                return ResourceManager.GetString("add_text", resourceCulture);
            }
        }
        
        public static string import_bootimg {
            get {
                return ResourceManager.GetString("import_bootimg", resourceCulture);
            }
        }
        
        public static string start_import {
            get {
                return ResourceManager.GetString("start_import", resourceCulture);
            }
        }
        
        public static string open_bootimg {
            get {
                return ResourceManager.GetString("open_bootimg", resourceCulture);
            }
        }
        
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        public static string select_a_satellite {
            get {
                return ResourceManager.GetString("select_a_satellite", resourceCulture);
            }
        }
        
        public static string satellite_detail {
            get {
                return ResourceManager.GetString("satellite_detail", resourceCulture);
            }
        }
        
        public static string choose_mode {
            get {
                return ResourceManager.GetString("choose_mode", resourceCulture);
            }
        }
        
        public static string doppler {
            get {
                return ResourceManager.GetString("doppler", resourceCulture);
            }
        }
        
        public static string u_band {
            get {
                return ResourceManager.GetString("u_band", resourceCulture);
            }
        }
        
        public static string v_band {
            get {
                return ResourceManager.GetString("v_band", resourceCulture);
            }
        }
        
        public static string manual_override {
            get {
                return ResourceManager.GetString("manual_override", resourceCulture);
            }
        }
        
        public static string uplink {
            get {
                return ResourceManager.GetString("uplink", resourceCulture);
            }
        }
        
        public static string downlink {
            get {
                return ResourceManager.GetString("downlink", resourceCulture);
            }
        }
        
        public static string tone {
            get {
                return ResourceManager.GetString("tone", resourceCulture);
            }
        }
        
        public static string none_if_empty {
            get {
                return ResourceManager.GetString("none_if_empty", resourceCulture);
            }
        }
        
        public static string update_satinfo {
            get {
                return ResourceManager.GetString("update_satinfo", resourceCulture);
            }
        }
        
        public static string insert_channel {
            get {
                return ResourceManager.GetString("insert_channel", resourceCulture);
            }
        }
        
        public static string code_group {
            get {
                return ResourceManager.GetString("code_group", resourceCulture);
            }
        }
        
        public static string restore {
            get {
                return ResourceManager.GetString("restore", resourceCulture);
            }
        }
        
        public static string tx_on_release_ptt {
            get {
                return ResourceManager.GetString("tx_on_release_ptt", resourceCulture);
            }
        }
        
        public static string tx_on_press_ptt {
            get {
                return ResourceManager.GetString("tx_on_press_ptt", resourceCulture);
            }
        }
        
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        public static string rw_chan_method {
            get {
                return ResourceManager.GetString("rw_chan_method", resourceCulture);
            }
        }
        
        public static string serial {
            get {
                return ResourceManager.GetString("serial", resourceCulture);
            }
        }
        
        public static string bt {
            get {
                return ResourceManager.GetString("bt", resourceCulture);
            }
        }
        
        public static string tx_allow {
            get {
                return ResourceManager.GetString("tx_allow", resourceCulture);
            }
        }
        
        public static string qtdqt_decode {
            get {
                return ResourceManager.GetString("qtdqt_decode", resourceCulture);
            }
        }
        
        public static string qtdqt_encode {
            get {
                return ResourceManager.GetString("qtdqt_encode", resourceCulture);
            }
        }
        
        public static string encrypt {
            get {
                return ResourceManager.GetString("encrypt", resourceCulture);
            }
        }
        
        public static string mode_set {
            get {
                return ResourceManager.GetString("mode_set", resourceCulture);
            }
        }
        
        public static string voice_remind {
            get {
                return ResourceManager.GetString("voice_remind", resourceCulture);
            }
        }
        
        public static string a_band_mode {
            get {
                return ResourceManager.GetString("a_band_mode", resourceCulture);
            }
        }
        
        public static string b_band_mode {
            get {
                return ResourceManager.GetString("b_band_mode", resourceCulture);
            }
        }
        
        public static string dtmf_sidetone {
            get {
                return ResourceManager.GetString("dtmf_sidetone", resourceCulture);
            }
        }
        
        public static string tx_id_delay {
            get {
                return ResourceManager.GetString("tx_id_delay", resourceCulture);
            }
        }
        
        public static string sidekey_short {
            get {
                return ResourceManager.GetString("sidekey_short", resourceCulture);
            }
        }
        
        public static string sidekey_long {
            get {
                return ResourceManager.GetString("sidekey_long", resourceCulture);
            }
        }
        
        public static string pass_rpt_tail_delay {
            get {
                return ResourceManager.GetString("pass_rpt_tail_delay", resourceCulture);
            }
        }
        
        public static string whether_to_play_voice_on_sos {
            get {
                return ResourceManager.GetString("whether_to_play_voice_on_sos", resourceCulture);
            }
        }
        
        public static string stop_send_on_busy {
            get {
                return ResourceManager.GetString("stop_send_on_busy", resourceCulture);
            }
        }
        
        public static string auto_lock {
            get {
                return ResourceManager.GetString("auto_lock", resourceCulture);
            }
        }
        
        public static string tx_my_id {
            get {
                return ResourceManager.GetString("tx_my_id", resourceCulture);
            }
        }
        
        public static string my_sos_voice {
            get {
                return ResourceManager.GetString("my_sos_voice", resourceCulture);
            }
        }
        
        public static string a_band_area {
            get {
                return ResourceManager.GetString("a_band_area", resourceCulture);
            }
        }
        
        public static string b_band_area {
            get {
                return ResourceManager.GetString("b_band_area", resourceCulture);
            }
        }
        
        public static string bt_mic_gain {
            get {
                return ResourceManager.GetString("bt_mic_gain", resourceCulture);
            }
        }
        
        public static string advanced {
            get {
                return ResourceManager.GetString("advanced", resourceCulture);
            }
        }
        
        public static string relay_mode {
            get {
                return ResourceManager.GetString("relay_mode", resourceCulture);
            }
        }
        
        public static string relay_speaker {
            get {
                return ResourceManager.GetString("relay_speaker", resourceCulture);
            }
        }
        
        public static string available_after_restart {
            get {
                return ResourceManager.GetString("available_after_restart", resourceCulture);
            }
        }
        
        public static string reset {
            get {
                return ResourceManager.GetString("reset", resourceCulture);
            }
        }
        
        public static string save_as_excel {
            get {
                return ResourceManager.GetString("save_as_excel", resourceCulture);
            }
        }
        
        public static string read_from_excel {
            get {
                return ResourceManager.GetString("read_from_excel", resourceCulture);
            }
        }
    }
}
