//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SenhaixFreqWriter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_en_us {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_en_us() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SenhaixFreqWriter.Properties.Resources.en-us", typeof(Resources_en_us).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        public static string abort {
            get {
                return ResourceManager.GetString("abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SenhaixFreqWriter.
        /// </summary>
        public static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto backup: .
        /// </summary>
        public static string auto_backup {
            get {
                return ResourceManager.GetString("auto_backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable automatic port selection.
        /// </summary>
        public static string auto_port_sel {
            get {
                return ResourceManager.GetString("auto_port_sel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -backup period.
        /// </summary>
        public static string backup_period {
            get {
                return ResourceManager.GetString("backup_period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect bluetooth.
        /// </summary>
        public static string bt_connection {
            get {
                return ResourceManager.GetString("bt_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin args:.
        /// </summary>
        public static string bt_plugin_args {
            get {
                return ResourceManager.GetString("bt_plugin_args", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BtPlugin Name:.
        /// </summary>
        public static string bt_plugin_name {
            get {
                return ResourceManager.GetString("bt_plugin_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese.
        /// </summary>
        public static string chinese {
            get {
                return ResourceManager.GetString("chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choose.
        /// </summary>
        public static string choose {
            get {
                return ResourceManager.GetString("choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Device.
        /// </summary>
        public static string choose_device {
            get {
                return ResourceManager.GetString("choose_device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have connected the programming cable before starting the software and there are no other USB serial devices, the software should have automatically selected the port for you.
        ///If the software did not select the port automatically, please follow these steps to choose the serial port:
        ///
        ///Windows:
        ///
        ///Make sure you have installed the corresponding driver for the programming cable.
        ///Open Device Manager and look for your programming cable under the &quot;Ports&quot; section; the name should be something like &quot;USB-SE [rest of string was truncated]&quot;;.
        /// </summary>
        public static string choose_help {
            get {
                return ResourceManager.GetString("choose_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Port.
        /// </summary>
        public static string choose_port {
            get {
                return ResourceManager.GetString("choose_port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit: .
        /// </summary>
        public static string commit {
            get {
                return ResourceManager.GetString("commit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compile Time: .
        /// </summary>
        public static string compile_time {
            get {
                return ResourceManager.GetString("compile_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to device.
        /// </summary>
        public static string conn_bt {
            get {
                return ResourceManager.GetString("conn_bt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable detailed debug output.
        /// </summary>
        public static string detailed_log {
            get {
                return ResourceManager.GetString("detailed_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable SSID filtering.
        /// </summary>
        public static string disable_ssid_filter {
            get {
                return ResourceManager.GetString("disable_ssid_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable weak signal restriction (Windows).
        /// </summary>
        public static string disable_weak_signal {
            get {
                return ResourceManager.GetString("disable_weak_signal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed!.
        /// </summary>
        public static string failed {
            get {
                return ResourceManager.GetString("failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hint: If you can’t find the target device on Windows, try restarting Bluetooth by clicking me~.
        /// </summary>
        public static string hint_bt {
            get {
                return ResourceManager.GetString("hint_bt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to choose?.
        /// </summary>
        public static string how2choose {
            get {
                return ResourceManager.GetString("how2choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Internal Version).
        /// </summary>
        public static string internal_version {
            get {
                return ResourceManager.GetString("internal_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Manually call plugin(advanced).
        /// </summary>
        public static string manual_call {
            get {
                return ResourceManager.GetString("manual_call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , max backups:.
        /// </summary>
        public static string max_backups {
            get {
                return ResourceManager.GetString("max_backups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open dir.
        /// </summary>
        public static string open_backup_dir {
            get {
                return ResourceManager.GetString("open_backup_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string port {
            get {
                return ResourceManager.GetString("port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repo.
        /// </summary>
        public static string repo {
            get {
                return ResourceManager.GetString("repo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPC Call.
        /// </summary>
        public static string rpc_call {
            get {
                return ResourceManager.GetString("rpc_call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan device.
        /// </summary>
        public static string scan_bt {
            get {
                return ResourceManager.GetString("scan_bt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Name.
        /// </summary>
        public static string ssid {
            get {
                return ResourceManager.GetString("ssid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data dir:.
        /// </summary>
        public static string storage_dir {
            get {
                return ResourceManager.GetString("storage_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please open with sudo!.
        /// </summary>
        public static string sudo {
            get {
                return ResourceManager.GetString("sudo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language: .
        /// </summary>
        public static string switch_language {
            get {
                return ResourceManager.GetString("switch_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks to....
        /// </summary>
        public static string thanksto {
            get {
                return ResourceManager.GetString("thanksto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: .
        /// </summary>
        public static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
    }
}
