namespace SHX_GT12_CPS;

public enum ENUM_COMMAND
{
    CMD_HANDSHAKE = 1,
    CMD_GETMODELTYPE = 2,
    CMD_CHECKPWD = 3,
    CMD_GETBANDRANGE = 70,
    CMD_READ = 82,
    CMD_WRITE = 87,
    CMD_INTOBOOTMODE = 85,
    CMD_OVER = 69,
    CMD_SENDLONGDATA = 5,
    CMD_OVERSENDLONGDATA = 6,
    CMD_INTOFLASHPROGRAM = 16,
    CMD_READFLASH = 17,
    CMD_WRITEFLASH = 18,
    CMD_ERASEFLASH = 19
}